# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classifierInterface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_classifierInterface(object):
    def setupUi(self, classifierInterface):
        classifierInterface.setObjectName("classifierInterface")
        classifierInterface.resize(1564, 1020)
        self.centralwidget = QtWidgets.QWidget(classifierInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(770, 10, 301, 210))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scalerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.scalerLabel.setObjectName("scalerLabel")
        self.horizontalLayout_3.addWidget(self.scalerLabel)
        self.scalerComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.scalerComboBox.setObjectName("scalerComboBox")
        self.scalerComboBox.addItem("")
        self.scalerComboBox.addItem("")
        self.scalerComboBox.addItem("")
        self.scalerComboBox.addItem("")
        self.scalerComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.scalerComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.reduceDimLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.reduceDimLabel.setObjectName("reduceDimLabel")
        self.horizontalLayout_5.addWidget(self.reduceDimLabel)
        self.reduceDimComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.reduceDimComboBox.setObjectName("reduceDimComboBox")
        self.reduceDimComboBox.addItem("")
        self.reduceDimComboBox.addItem("")
        self.reduceDimComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.reduceDimComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clusterLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.clusterLabel.setObjectName("clusterLabel")
        self.horizontalLayout_2.addWidget(self.clusterLabel)
        self.clusterComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.clusterComboBox.setObjectName("clusterComboBox")
        self.clusterComboBox.addItem("")
        self.clusterComboBox.addItem("")
        self.clusterComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.clusterComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.needN_clusterLayout = QtWidgets.QHBoxLayout()
        self.needN_clusterLayout.setObjectName("needN_clusterLayout")
        self.n_clusterLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.n_clusterLabel.setObjectName("n_clusterLabel")
        self.needN_clusterLayout.addWidget(self.n_clusterLabel)
        self.n_clusterLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.n_clusterLineEdit.setObjectName("n_clusterLineEdit")
        self.needN_clusterLayout.addWidget(self.n_clusterLineEdit)
        self.verticalLayout.addLayout(self.needN_clusterLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.min_samplesLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.min_samplesLabel.setObjectName("min_samplesLabel")
        self.horizontalLayout.addWidget(self.min_samplesLabel)
        self.min_samplesLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.min_samplesLineEdit.setObjectName("min_samplesLineEdit")
        self.horizontalLayout.addWidget(self.min_samplesLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.epsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.epsLabel.setObjectName("epsLabel")
        self.horizontalLayout_4.addWidget(self.epsLabel)
        self.epsLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.epsLineEdit.setObjectName("epsLineEdit")
        self.horizontalLayout_4.addWidget(self.epsLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.classifyPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.classifyPushButton.setObjectName("classifyPushButton")
        self.verticalLayout.addWidget(self.classifyPushButton)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 411))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.visualizaionField = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.visualizaionField.setContentsMargins(0, 0, 0, 0)
        self.visualizaionField.setObjectName("visualizaionField")
        self.stateTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.stateTextEdit.setGeometry(QtCore.QRect(770, 240, 301, 171))
        self.stateTextEdit.setObjectName("stateTextEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 440, 1541, 521))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        classifierInterface.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(classifierInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1564, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.save = QtWidgets.QMenu(self.menu)
        self.save.setObjectName("save")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        classifierInterface.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(classifierInterface)
        self.statusBar.setObjectName("statusBar")
        classifierInterface.setStatusBar(self.statusBar)
        self.actionCollect_and_stuff_data = QtWidgets.QAction(classifierInterface)
        self.actionCollect_and_stuff_data.setObjectName("actionCollect_and_stuff_data")
        self.actionSolveAverageValues = QtWidgets.QAction(classifierInterface)
        self.actionSolveAverageValues.setObjectName("actionSolveAverageValues")
        self.actionScaleSize = QtWidgets.QAction(classifierInterface)
        self.actionScaleSize.setObjectName("actionScaleSize")
        self.actionSaveImage = QtWidgets.QAction(classifierInterface)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionSaveClusters = QtWidgets.QAction(classifierInterface)
        self.actionSaveClusters.setObjectName("actionSaveClusters")
        self.save.addAction(self.actionSaveImage)
        self.save.addAction(self.actionSaveClusters)
        self.menu.addAction(self.save.menuAction())
        self.menu_2.addAction(self.actionScaleSize)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(classifierInterface)
        QtCore.QMetaObject.connectSlotsByName(classifierInterface)

    def retranslateUi(self, classifierInterface):
        _translate = QtCore.QCoreApplication.translate
        classifierInterface.setWindowTitle(_translate("classifierInterface", "MainWindow"))
        self.scalerLabel.setText(_translate("classifierInterface", "scaler:"))
        self.scalerComboBox.setItemText(0, _translate("classifierInterface", "None"))
        self.scalerComboBox.setItemText(1, _translate("classifierInterface", "MinMaxScaler"))
        self.scalerComboBox.setItemText(2, _translate("classifierInterface", "RobustScaler"))
        self.scalerComboBox.setItemText(3, _translate("classifierInterface", "StandardScaler"))
        self.scalerComboBox.setItemText(4, _translate("classifierInterface", "Normalizer"))
        self.reduceDimLabel.setText(_translate("classifierInterface", "reduceDimension:"))
        self.reduceDimComboBox.setItemText(0, _translate("classifierInterface", "None"))
        self.reduceDimComboBox.setItemText(1, _translate("classifierInterface", "PCA"))
        self.reduceDimComboBox.setItemText(2, _translate("classifierInterface", "TSNE"))
        self.clusterLabel.setText(_translate("classifierInterface", "clusterAlgorithm:"))
        self.clusterComboBox.setItemText(0, _translate("classifierInterface", "KMeans"))
        self.clusterComboBox.setItemText(1, _translate("classifierInterface", "Agglomerative"))
        self.clusterComboBox.setItemText(2, _translate("classifierInterface", "DBSCAN"))
        self.n_clusterLabel.setText(_translate("classifierInterface", "n_clusters:"))
        self.min_samplesLabel.setText(_translate("classifierInterface", "min_samples:"))
        self.epsLabel.setText(_translate("classifierInterface", "eps:            "))
        self.classifyPushButton.setText(_translate("classifierInterface", "classify"))
        self.menu.setTitle(_translate("classifierInterface", "파일"))
        self.save.setTitle(_translate("classifierInterface", "save"))
        self.menu_2.setTitle(_translate("classifierInterface", "설정"))
        self.actionCollect_and_stuff_data.setText(_translate("classifierInterface", "collect and stuff data"))
        self.actionSolveAverageValues.setText(_translate("classifierInterface", "solveAverageValues"))
        self.actionScaleSize.setText(_translate("classifierInterface", "scaleSize"))
        self.actionSaveImage.setText(_translate("classifierInterface", "saveImage"))
        self.actionSaveClusters.setText(_translate("classifierInterface", "saveClusters"))

